src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Post", inversedBy="comments")
     * @ORM\JoinColumn(nullable=true)
     */
    private $post;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $body;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     */
    private $createdAt;

    public function getId()
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function setPost(Post $post)
    {
        $this->post = $post;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $heading;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post")
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     */
    private $createdAt;

    public function getId()
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(string $heading): self
    {
        $this->heading = $heading;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function getParagraphs(): array
    {
        return array_filter(explode("\n", $this->body));
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    // An excerpts is at most the n first (multibyte-)characters of the body.
    public function getExcerpt($n = 120): string
    {
        if (mb_strlen ($this->body) > $n) {
            return mb_substr ($this->body, 0, $n) . '…';
        }

        return $this->body;
    }

    public function addComment(Comment $comment)
    {
        $this->comments[] = $comment;
        $comment->setPost($this);
    }

    public function getComments()
    {
        return $this->comments;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Controller/CommentController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Post;
use App\Entity\Comment;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Doctrine\ORM\EntityManagerInterface;

class CommentController extends Controller
{
    // TODO: Use a form object both for creating the form and saving its content here.
    public function create(EntityManagerInterface $em, Request $request)
    {
        $author = $request->request->get('form')['author'];
        $body = $request->request->get('form')['body'];
        $postId = $request->request->get('form')['id'];

        $correspondingPost = $em->getRepository(Post::class)->find($postId);

        $comment = new Comment();
        $comment
            ->setAuthor($author)
            ->setBody($body)
            ->setPost($correspondingPost)
            ->setCreatedAt(new \Datetime());

        $em->persist($comment);
        $em->flush();

        return $this->redirectToRoute('app_post_view', ['id' => $postId]);
    }
}

src/Controller/PostController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use App\Entity\Post;
use App\Entity\Comment;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PostController extends Controller
{
    public function list($page)
    {
        $posts = $this->getDoctrine()->getRepository(Post::class)->findPage($page);
        $pageCount = $this->getDoctrine()->getRepository(Post::class)->countPages();

        return $this->render('post/list.html.twig', [
            'posts' => $posts,
            'currentPage' => $page,
            'pageNumbers' => range(1, $pageCount),
        ]);
    }

    public function view($id)
    {
        $commentForm = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('app_comment_create'))
            ->setMethod('POST')
            ->add('author', TextType::class, ['label' => 'Your name'])
            ->add('body', TextareaType::class, ['label' => 'Message'])
            ->add('id', HiddenType::class, ['data' => $id])
            ->add('save', SubmitType::class, ['label' => 'Post comment'])
            ->getForm()
            ->createView();

        $post = $this->getDoctrine()->getRepository(Post::class)->find($id);
        // Not sure how to get `order by' into default hydration, so we're doing this for now.
        $comments = $this->getDoctrine()->getRepository(Comment::class)
            ->findBy(['post' => $id], ['createdAt' => 'DESC']);
        return $this->render('post/view.html.twig', [
            'post' => $post,
            'comments' => $comments,
            'commentForm' => $commentForm,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %} - Happy blog</title>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=yes">
	<link href="{{ asset('assets/common.css') }}" rel="stylesheet">
	{% block stylesheets %}{% endblock %}
</head>
<body>

<header>
	<h1><a href="{{ path('app_post_list') }}">Happy blog</a></h1>
</header>

<main>
	{% block body %}{% endblock %}
</main>

{% block javascripts %}{% endblock %}
</body>
</html>

templates/post/list.html.twig
{% extends 'base.html.twig' %}
{% block title %}List of posts{% endblock %}
{% block body %}

	{% for post in posts %}
		<article>
			<h2><a href="{{ path('app_post_view', {'id': post.id}) }}">{{ post.heading }}</a></h2>
			<time>Posted {{ post.createdAt | date('Y-m-d') }}</time>
			<p>{{ post.excerpt }}</p>
		</article>
	{% endfor %}

	{% spaceless %}
	<div class="pagination">
		{% if currentPage != 1 %}
			<a class="pagination-link" href="{{ path('app_post_list', {'page': currentPage-1}) }}">&lt;</a>
		{% endif %}

		{% for pageNumber in pageNumbers %}
			{% if pageNumber == currentPage %}
				<span class="pagination-link pagination-link-active">{{ pageNumber }}</span>
			{% else %}
				<a class="pagination-link" href="{{ path('app_post_list', {'page': pageNumber}) }}">{{ pageNumber }}</a>
			{% endif %}
		{% endfor %}

		{% if currentPage != max(pageNumbers) %}
			<a class="pagination-link" href="{{ path('app_post_list', {'page': currentPage+1}) }}">&gt;</a>
		{% endif %}
	</div>
	{% endspaceless %}

{% endblock %}

templates/post/view.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ post.heading }}{% endblock %}
{% block body %}

	<article>
		<h2><a href="{{ path('app_post_view', {'id': post.id}) }}">{{ post.heading }}</a></h2>
		<time>Posted {{ post.createdAt | date('Y-m-d') }}</time>
		{% for paragraph in post.paragraphs %}
			<p>{{ paragraph }}</p>
		{% endfor %}
		<p class="signature">—the happy crew</p>
	</article>

	<p>Feel like you have something valuable to add to the conversation? Open yourself up—type it out. Just remember, keep it happy!</p>
	{{ form_start(commentForm) }}
		{{ form_widget(commentForm) }}
	{{ form_end(commentForm) }}

	{% for comment in comments %}
		<div class="comment">
			<div>
				<span class="comment-author">{{ comment.author }}</span> <time>{{ comment.createdAt | date('Y-m-d') }}</time>
			</div>
			<p>{{ comment.body }}</p>
		</div>
	{% else %}
		<p>There are no comments for this post… yet!</p>
	{% endfor %}

{% endblock %}